### ISSUE TITLE
Documentation grammar and spelling correction 

### ISSUE THREAD

**Issue by mkarjun** [mkarjun/TerraformDocs#2]
Review the existing document and do a spell and grammar check.

**Comment by khushii2609** [comment]
hey, i am new to open source, and i believe i can help you with the issue. So, can you assign this issue to me.

**Comment by mkarjun** [comment]
@khushii2609 Could you please the status.

Thanks

**Comment by khushii2609** [comment]
I have pushed the changes, hope I have done the right way. If any issues do let me know.

**Comment by mkarjun** [comment]
Hi @khushii2609 , I didn't see any pull requests, maybe it got updated to the local machine🤔

**Comment by khushii2609** [comment]
made the pull request.

**Comment by mkarjun** [comment]
@khushii2609 Thanks for your contribution.☺️
